//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 10/8/2014 5:59:03 PM
namespace Microsoft.OneNote.Api
{
    /// <summary>
    /// There are no comments for OneNoteApi in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("OneNoteApi")]
    public partial class OneNoteApi : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new OneNoteApi object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public OneNoteApi(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Microsoft.OneNote.Api", "Microsoft.OneNote.Api");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("Microsoft.OneNote.Api", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Microsoft.OneNote.Api.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Microsoft.OneNote.Api.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Notebooks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<Notebook> Notebooks
        {
            get
            {
                if ((this._Notebooks == null))
                {
                    this._Notebooks = base.CreateQuery<Notebook>("notebooks");
                }
                return this._Notebooks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<Notebook> _Notebooks;
        /// <summary>
        /// There are no comments for SectionGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<SectionGroup> SectionGroups
        {
            get
            {
                if ((this._SectionGroups == null))
                {
                    this._SectionGroups = base.CreateQuery<SectionGroup>("sectionGroups");
                }
                return this._SectionGroups;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<SectionGroup> _SectionGroups;
        /// <summary>
        /// There are no comments for Sections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<Section> Sections
        {
            get
            {
                if ((this._Sections == null))
                {
                    this._Sections = base.CreateQuery<Section>("sections");
                }
                return this._Sections;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<Section> _Sections;
        /// <summary>
        /// There are no comments for Pages in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<Page> Pages
        {
            get
            {
                if ((this._Pages == null))
                {
                    this._Pages = base.CreateQuery<Page>("pages");
                }
                return this._Pages;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<Page> _Pages;
        /// <summary>
        /// There are no comments for Notebooks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public void AddToNotebooks(Notebook notebook)
        {
            base.AddObject("notebooks", notebook);
        }
        /// <summary>
        /// There are no comments for SectionGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public void AddToSectionGroups(SectionGroup sectionGroup)
        {
            base.AddObject("sectionGroups", sectionGroup);
        }
        /// <summary>
        /// There are no comments for Sections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public void AddToSections(Section section)
        {
            base.AddObject("sections", section);
        }
        /// <summary>
        /// There are no comments for Pages in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public void AddToPages(Page page)
        {
            base.AddObject("pages", page);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""Microsoft.OneNote.Api"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Notebook"">
        <Key>
          <PropertyRef Name=""id"" />
        </Key>
        <Property Name=""isDefault"" Type=""Edm.Boolean"" />
        <Property Name=""userRole"" Type=""Microsoft.OneNote.Api.UserRole"" />
        <Property Name=""isShared"" Type=""Edm.Boolean"" />
        <Property Name=""sectionsUrl"" Type=""Edm.String"" />
        <Property Name=""sectionGroupsUrl"" Type=""Edm.String"" />
        <Property Name=""links"" Type=""Microsoft.OneNote.Api.NotebookLinks"" />
        <Property Name=""name"" Type=""Edm.String"" />
        <Property Name=""self"" Type=""Edm.String"" />
        <Property Name=""createdBy"" Type=""Edm.String"" />
        <Property Name=""lastModifiedBy"" Type=""Edm.String"" />
        <Property Name=""lastModifiedTime"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""id"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""createdTime"" Type=""Edm.DateTimeOffset"" />
        <NavigationProperty Name=""sections"" Type=""Collection(Microsoft.OneNote.Api.Section)"" />
        <NavigationProperty Name=""sectionGroups"" Type=""Collection(Microsoft.OneNote.Api.SectionGroup)"" />
      </EntityType>
      <EntityType Name=""SectionGroup"">
        <Key>
          <PropertyRef Name=""id"" />
        </Key>
        <Property Name=""sectionsUrl"" Type=""Edm.String"" />
        <Property Name=""sectionGroupsUrl"" Type=""Edm.String"" />
        <Property Name=""name"" Type=""Edm.String"" />
        <Property Name=""self"" Type=""Edm.String"" />
        <Property Name=""createdBy"" Type=""Edm.String"" />
        <Property Name=""lastModifiedBy"" Type=""Edm.String"" />
        <Property Name=""lastModifiedTime"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""id"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""createdTime"" Type=""Edm.DateTimeOffset"" />
        <NavigationProperty Name=""parentNotebook"" Type=""Microsoft.OneNote.Api.Notebook"" />
        <NavigationProperty Name=""parentSectionGroup"" Type=""Microsoft.OneNote.Api.SectionGroup"" />
        <NavigationProperty Name=""sections"" Type=""Collection(Microsoft.OneNote.Api.Section)"" />
        <NavigationProperty Name=""sectionGroups"" Type=""Collection(Microsoft.OneNote.Api.SectionGroup)"" />
      </EntityType>
      <EntityType Name=""Section"">
        <Key>
          <PropertyRef Name=""id"" />
        </Key>
        <Property Name=""isDefault"" Type=""Edm.Boolean"" />
        <Property Name=""pagesUrl"" Type=""Edm.String"" />
        <Property Name=""name"" Type=""Edm.String"" />
        <Property Name=""self"" Type=""Edm.String"" />
        <Property Name=""createdBy"" Type=""Edm.String"" />
        <Property Name=""lastModifiedBy"" Type=""Edm.String"" />
        <Property Name=""lastModifiedTime"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""id"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""createdTime"" Type=""Edm.DateTimeOffset"" />
        <NavigationProperty Name=""parentNotebook"" Type=""Microsoft.OneNote.Api.Notebook"" />
        <NavigationProperty Name=""parentSectionGroup"" Type=""Microsoft.OneNote.Api.SectionGroup"" />
        <NavigationProperty Name=""pages"" Type=""Collection(Microsoft.OneNote.Api.Page)"" />
      </EntityType>
      <EntityType Name=""Page"">
        <Key>
          <PropertyRef Name=""id"" />
        </Key>
        <Property Name=""title"" Type=""Edm.String"" />
        <Property Name=""createdByAppId"" Type=""Edm.String"" />
        <Property Name=""links"" Type=""Microsoft.OneNote.Api.PageLinks"" />
        <Property Name=""id"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""createdTime"" Type=""Edm.DateTimeOffset"" />
        <NavigationProperty Name=""parentSection"" Type=""Microsoft.OneNote.Api.Section"" />
        <NavigationProperty Name=""parentNotebook"" Type=""Microsoft.OneNote.Api.Notebook"" />
      </EntityType>
      <ComplexType Name=""NotebookLinks"">
        <Property Name=""oneNoteClientUrl"" Type=""Microsoft.OneNote.Api.ExternalLink"" />
        <Property Name=""oneNoteWebUrl"" Type=""Microsoft.OneNote.Api.ExternalLink"" />
      </ComplexType>
      <ComplexType Name=""PageLinks"">
        <Property Name=""oneNoteClientUrl"" Type=""Microsoft.OneNote.Api.ExternalLink"" />
        <Property Name=""oneNoteWebUrl"" Type=""Microsoft.OneNote.Api.ExternalLink"" />
      </ComplexType>
      <ComplexType Name=""ExternalLink"">
        <Property Name=""href"" Type=""Edm.String"" />
      </ComplexType>
      <ComplexType Name=""Diagnostic"">
        <Property Name=""message"" Type=""Edm.String"" />
        <Property Name=""url"" Type=""Edm.String"" />
      </ComplexType>
      <EnumType Name=""UserRole"">
        <Member Name=""Owner"" Value=""0"" />
        <Member Name=""Contributor"" Value=""1"" />
        <Member Name=""Reader"" Value=""2"" />
        <Member Name=""None"" Value=""-1"" />
      </EnumType>
      <EntityContainer Name=""OneNoteApi"">
        <EntitySet Name=""notebooks"" EntityType=""Microsoft.OneNote.Api.Notebook"">
          <NavigationPropertyBinding Path=""sections"" Target=""sections"" />
          <NavigationPropertyBinding Path=""sectionGroups"" Target=""sectionGroups"" />
        </EntitySet>
        <EntitySet Name=""sectionGroups"" EntityType=""Microsoft.OneNote.Api.SectionGroup"">
          <NavigationPropertyBinding Path=""parentNotebook"" Target=""notebooks"" />
          <NavigationPropertyBinding Path=""parentSectionGroup"" Target=""sectionGroups"" />
          <NavigationPropertyBinding Path=""sections"" Target=""sections"" />
          <NavigationPropertyBinding Path=""sectionGroups"" Target=""sectionGroups"" />
        </EntitySet>
        <EntitySet Name=""sections"" EntityType=""Microsoft.OneNote.Api.Section"">
          <NavigationPropertyBinding Path=""parentNotebook"" Target=""notebooks"" />
          <NavigationPropertyBinding Path=""parentSectionGroup"" Target=""sectionGroups"" />
          <NavigationPropertyBinding Path=""pages"" Target=""pages"" />
        </EntitySet>
        <EntitySet Name=""pages"" EntityType=""Microsoft.OneNote.Api.Page"">
          <NavigationPropertyBinding Path=""parentSection"" Target=""sections"" />
          <NavigationPropertyBinding Path=""parentNotebook"" Target=""notebooks"" />
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for NotebookSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("NotebookSingle")]
    public partial class NotebookSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Notebook>
    {
        /// <summary>
        /// Initialize a new NotebookSingle object.
        /// </summary>
        public NotebookSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new NotebookSingle object.
        /// </summary>
        public NotebookSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
        /// <summary>
        /// There are no comments for Sections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OneNote.Api.Section> Sections
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Sections == null))
                {
                    this._Sections = Context.CreateQuery<global::Microsoft.OneNote.Api.Section>(GetPath("sections"));
                }
                return this._Sections;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OneNote.Api.Section> _Sections;
        /// <summary>
        /// There are no comments for SectionGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OneNote.Api.SectionGroup> SectionGroups
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._SectionGroups == null))
                {
                    this._SectionGroups = Context.CreateQuery<global::Microsoft.OneNote.Api.SectionGroup>(GetPath("sectionGroups"));
                }
                return this._SectionGroups;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OneNote.Api.SectionGroup> _SectionGroups;
    }
    /// <summary>
    /// There are no comments for Notebook in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Notebook")]
    public partial class Notebook
    {
        /// <summary>
        /// Create a new Notebook object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static Notebook CreateNotebook(string ID)
        {
            Notebook notebook = new Notebook();
            notebook.Id = ID;
            return notebook;
        }
        /// <summary>
        /// There are no comments for Property IsDefault in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("isDefault")]
        public global::System.Nullable<bool> IsDefault
        {
            get
            {
                return this._IsDefault;
            }
            set
            {
                this.OnIsDefaultChanging(value);
                this._IsDefault = value;
                this.OnIsDefaultChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Nullable<bool> _IsDefault;
        partial void OnIsDefaultChanging(global::System.Nullable<bool> value);
        partial void OnIsDefaultChanged();
        /// <summary>
        /// There are no comments for Property UserRole in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("userRole")]
        public global::System.Nullable<global::Microsoft.OneNote.Api.UserRole> UserRole
        {
            get
            {
                return this._UserRole;
            }
            set
            {
                this.OnUserRoleChanging(value);
                this._UserRole = value;
                this.OnUserRoleChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Nullable<global::Microsoft.OneNote.Api.UserRole> _UserRole;
        partial void OnUserRoleChanging(global::System.Nullable<global::Microsoft.OneNote.Api.UserRole> value);
        partial void OnUserRoleChanged();
        /// <summary>
        /// There are no comments for Property IsShared in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("isShared")]
        public global::System.Nullable<bool> IsShared
        {
            get
            {
                return this._IsShared;
            }
            set
            {
                this.OnIsSharedChanging(value);
                this._IsShared = value;
                this.OnIsSharedChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Nullable<bool> _IsShared;
        partial void OnIsSharedChanging(global::System.Nullable<bool> value);
        partial void OnIsSharedChanged();
        /// <summary>
        /// There are no comments for Property SectionsUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("sectionsUrl")]
        public string SectionsUrl
        {
            get
            {
                return this._SectionsUrl;
            }
            set
            {
                this.OnSectionsUrlChanging(value);
                this._SectionsUrl = value;
                this.OnSectionsUrlChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _SectionsUrl;
        partial void OnSectionsUrlChanging(string value);
        partial void OnSectionsUrlChanged();
        /// <summary>
        /// There are no comments for Property SectionGroupsUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("sectionGroupsUrl")]
        public string SectionGroupsUrl
        {
            get
            {
                return this._SectionGroupsUrl;
            }
            set
            {
                this.OnSectionGroupsUrlChanging(value);
                this._SectionGroupsUrl = value;
                this.OnSectionGroupsUrlChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _SectionGroupsUrl;
        partial void OnSectionGroupsUrlChanging(string value);
        partial void OnSectionGroupsUrlChanged();
        /// <summary>
        /// There are no comments for Property Links in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("links")]
        public global::Microsoft.OneNote.Api.NotebookLinks Links
        {
            get
            {
                return this._Links;
            }
            set
            {
                this.OnLinksChanging(value);
                this._Links = value;
                this.OnLinksChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OneNote.Api.NotebookLinks _Links;
        partial void OnLinksChanging(global::Microsoft.OneNote.Api.NotebookLinks value);
        partial void OnLinksChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Self in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("self")]
        public string Self
        {
            get
            {
                return this._Self;
            }
            set
            {
                this.OnSelfChanging(value);
                this._Self = value;
                this.OnSelfChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Self;
        partial void OnSelfChanging(string value);
        partial void OnSelfChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("createdBy")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property LastModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("lastModifiedBy")]
        public string LastModifiedBy
        {
            get
            {
                return this._LastModifiedBy;
            }
            set
            {
                this.OnLastModifiedByChanging(value);
                this._LastModifiedBy = value;
                this.OnLastModifiedByChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _LastModifiedBy;
        partial void OnLastModifiedByChanging(string value);
        partial void OnLastModifiedByChanged();
        /// <summary>
        /// There are no comments for Property LastModifiedTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("lastModifiedTime")]
        public global::System.Nullable<global::System.DateTimeOffset> LastModifiedTime
        {
            get
            {
                return this._LastModifiedTime;
            }
            set
            {
                this.OnLastModifiedTimeChanging(value);
                this._LastModifiedTime = value;
                this.OnLastModifiedTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _LastModifiedTime;
        partial void OnLastModifiedTimeChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnLastModifiedTimeChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("id")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("createdTime")]
        public global::System.Nullable<global::System.DateTimeOffset> CreatedTime
        {
            get
            {
                return this._CreatedTime;
            }
            set
            {
                this.OnCreatedTimeChanging(value);
                this._CreatedTime = value;
                this.OnCreatedTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreatedTime;
        partial void OnCreatedTimeChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedTimeChanged();
        /// <summary>
        /// There are no comments for Property Sections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("sections")]
        public global::System.Collections.ObjectModel.Collection<global::Microsoft.OneNote.Api.Section> Sections
        {
            get
            {
                return this._Sections;
            }
            set
            {
                this.OnSectionsChanging(value);
                this._Sections = value;
                this.OnSectionsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.OneNote.Api.Section> _Sections = new global::System.Collections.ObjectModel.Collection<global::Microsoft.OneNote.Api.Section>();
        partial void OnSectionsChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.OneNote.Api.Section> value);
        partial void OnSectionsChanged();
        /// <summary>
        /// There are no comments for Property SectionGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("sectionGroups")]
        public global::System.Collections.ObjectModel.Collection<global::Microsoft.OneNote.Api.SectionGroup> SectionGroups
        {
            get
            {
                return this._SectionGroups;
            }
            set
            {
                this.OnSectionGroupsChanging(value);
                this._SectionGroups = value;
                this.OnSectionGroupsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.OneNote.Api.SectionGroup> _SectionGroups = new global::System.Collections.ObjectModel.Collection<global::Microsoft.OneNote.Api.SectionGroup>();
        partial void OnSectionGroupsChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.OneNote.Api.SectionGroup> value);
        partial void OnSectionGroupsChanged();
    }
    /// <summary>
    /// There are no comments for SectionGroupSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("SectionGroupSingle")]
    public partial class SectionGroupSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<SectionGroup>
    {
        /// <summary>
        /// Initialize a new SectionGroupSingle object.
        /// </summary>
        public SectionGroupSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new SectionGroupSingle object.
        /// </summary>
        public SectionGroupSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
        /// <summary>
        /// There are no comments for ParentNotebook in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OneNote.Api.NotebookSingle ParentNotebook
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ParentNotebook == null))
                {
                    this._ParentNotebook = new global::Microsoft.OneNote.Api.NotebookSingle(this.Context, GetPath("parentNotebook"));
                }
                return this._ParentNotebook;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OneNote.Api.NotebookSingle _ParentNotebook;
        /// <summary>
        /// There are no comments for ParentSectionGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OneNote.Api.SectionGroupSingle ParentSectionGroup
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ParentSectionGroup == null))
                {
                    this._ParentSectionGroup = new global::Microsoft.OneNote.Api.SectionGroupSingle(this.Context, GetPath("parentSectionGroup"));
                }
                return this._ParentSectionGroup;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OneNote.Api.SectionGroupSingle _ParentSectionGroup;
        /// <summary>
        /// There are no comments for Sections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OneNote.Api.Section> Sections
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Sections == null))
                {
                    this._Sections = Context.CreateQuery<global::Microsoft.OneNote.Api.Section>(GetPath("sections"));
                }
                return this._Sections;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OneNote.Api.Section> _Sections;
        /// <summary>
        /// There are no comments for SectionGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OneNote.Api.SectionGroup> SectionGroups
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._SectionGroups == null))
                {
                    this._SectionGroups = Context.CreateQuery<global::Microsoft.OneNote.Api.SectionGroup>(GetPath("sectionGroups"));
                }
                return this._SectionGroups;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OneNote.Api.SectionGroup> _SectionGroups;
    }
    /// <summary>
    /// There are no comments for SectionGroup in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("SectionGroup")]
    public partial class SectionGroup
    {
        /// <summary>
        /// Create a new SectionGroup object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static SectionGroup CreateSectionGroup(string ID)
        {
            SectionGroup sectionGroup = new SectionGroup();
            sectionGroup.Id = ID;
            return sectionGroup;
        }
        /// <summary>
        /// There are no comments for Property SectionsUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("sectionsUrl")]
        public string SectionsUrl
        {
            get
            {
                return this._SectionsUrl;
            }
            set
            {
                this.OnSectionsUrlChanging(value);
                this._SectionsUrl = value;
                this.OnSectionsUrlChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _SectionsUrl;
        partial void OnSectionsUrlChanging(string value);
        partial void OnSectionsUrlChanged();
        /// <summary>
        /// There are no comments for Property SectionGroupsUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("sectionGroupsUrl")]
        public string SectionGroupsUrl
        {
            get
            {
                return this._SectionGroupsUrl;
            }
            set
            {
                this.OnSectionGroupsUrlChanging(value);
                this._SectionGroupsUrl = value;
                this.OnSectionGroupsUrlChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _SectionGroupsUrl;
        partial void OnSectionGroupsUrlChanging(string value);
        partial void OnSectionGroupsUrlChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Self in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("self")]
        public string Self
        {
            get
            {
                return this._Self;
            }
            set
            {
                this.OnSelfChanging(value);
                this._Self = value;
                this.OnSelfChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Self;
        partial void OnSelfChanging(string value);
        partial void OnSelfChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("createdBy")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property LastModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("lastModifiedBy")]
        public string LastModifiedBy
        {
            get
            {
                return this._LastModifiedBy;
            }
            set
            {
                this.OnLastModifiedByChanging(value);
                this._LastModifiedBy = value;
                this.OnLastModifiedByChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _LastModifiedBy;
        partial void OnLastModifiedByChanging(string value);
        partial void OnLastModifiedByChanged();
        /// <summary>
        /// There are no comments for Property LastModifiedTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("lastModifiedTime")]
        public global::System.Nullable<global::System.DateTimeOffset> LastModifiedTime
        {
            get
            {
                return this._LastModifiedTime;
            }
            set
            {
                this.OnLastModifiedTimeChanging(value);
                this._LastModifiedTime = value;
                this.OnLastModifiedTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _LastModifiedTime;
        partial void OnLastModifiedTimeChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnLastModifiedTimeChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("id")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("createdTime")]
        public global::System.Nullable<global::System.DateTimeOffset> CreatedTime
        {
            get
            {
                return this._CreatedTime;
            }
            set
            {
                this.OnCreatedTimeChanging(value);
                this._CreatedTime = value;
                this.OnCreatedTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreatedTime;
        partial void OnCreatedTimeChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedTimeChanged();
        /// <summary>
        /// There are no comments for Property ParentNotebook in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("parentNotebook")]
        public global::Microsoft.OneNote.Api.Notebook ParentNotebook
        {
            get
            {
                return this._ParentNotebook;
            }
            set
            {
                this.OnParentNotebookChanging(value);
                this._ParentNotebook = value;
                this.OnParentNotebookChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OneNote.Api.Notebook _ParentNotebook;
        partial void OnParentNotebookChanging(global::Microsoft.OneNote.Api.Notebook value);
        partial void OnParentNotebookChanged();
        /// <summary>
        /// There are no comments for Property ParentSectionGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("parentSectionGroup")]
        public global::Microsoft.OneNote.Api.SectionGroup ParentSectionGroup
        {
            get
            {
                return this._ParentSectionGroup;
            }
            set
            {
                this.OnParentSectionGroupChanging(value);
                this._ParentSectionGroup = value;
                this.OnParentSectionGroupChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OneNote.Api.SectionGroup _ParentSectionGroup;
        partial void OnParentSectionGroupChanging(global::Microsoft.OneNote.Api.SectionGroup value);
        partial void OnParentSectionGroupChanged();
        /// <summary>
        /// There are no comments for Property Sections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("sections")]
        public global::System.Collections.ObjectModel.Collection<global::Microsoft.OneNote.Api.Section> Sections
        {
            get
            {
                return this._Sections;
            }
            set
            {
                this.OnSectionsChanging(value);
                this._Sections = value;
                this.OnSectionsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.OneNote.Api.Section> _Sections = new global::System.Collections.ObjectModel.Collection<global::Microsoft.OneNote.Api.Section>();
        partial void OnSectionsChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.OneNote.Api.Section> value);
        partial void OnSectionsChanged();
        /// <summary>
        /// There are no comments for Property SectionGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("sectionGroups")]
        public global::System.Collections.ObjectModel.Collection<global::Microsoft.OneNote.Api.SectionGroup> SectionGroups
        {
            get
            {
                return this._SectionGroups;
            }
            set
            {
                this.OnSectionGroupsChanging(value);
                this._SectionGroups = value;
                this.OnSectionGroupsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.OneNote.Api.SectionGroup> _SectionGroups = new global::System.Collections.ObjectModel.Collection<global::Microsoft.OneNote.Api.SectionGroup>();
        partial void OnSectionGroupsChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.OneNote.Api.SectionGroup> value);
        partial void OnSectionGroupsChanged();
    }
    /// <summary>
    /// There are no comments for SectionSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("SectionSingle")]
    public partial class SectionSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Section>
    {
        /// <summary>
        /// Initialize a new SectionSingle object.
        /// </summary>
        public SectionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new SectionSingle object.
        /// </summary>
        public SectionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
        /// <summary>
        /// There are no comments for ParentNotebook in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OneNote.Api.NotebookSingle ParentNotebook
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ParentNotebook == null))
                {
                    this._ParentNotebook = new global::Microsoft.OneNote.Api.NotebookSingle(this.Context, GetPath("parentNotebook"));
                }
                return this._ParentNotebook;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OneNote.Api.NotebookSingle _ParentNotebook;
        /// <summary>
        /// There are no comments for ParentSectionGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OneNote.Api.SectionGroupSingle ParentSectionGroup
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ParentSectionGroup == null))
                {
                    this._ParentSectionGroup = new global::Microsoft.OneNote.Api.SectionGroupSingle(this.Context, GetPath("parentSectionGroup"));
                }
                return this._ParentSectionGroup;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OneNote.Api.SectionGroupSingle _ParentSectionGroup;
        /// <summary>
        /// There are no comments for Pages in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OneNote.Api.Page> Pages
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Pages == null))
                {
                    this._Pages = Context.CreateQuery<global::Microsoft.OneNote.Api.Page>(GetPath("pages"));
                }
                return this._Pages;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OneNote.Api.Page> _Pages;
    }
    /// <summary>
    /// There are no comments for Section in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Section")]
    public partial class Section
    {
        /// <summary>
        /// Create a new Section object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static Section CreateSection(string ID)
        {
            Section section = new Section();
            section.Id = ID;
            return section;
        }
        /// <summary>
        /// There are no comments for Property IsDefault in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("isDefault")]
        public global::System.Nullable<bool> IsDefault
        {
            get
            {
                return this._IsDefault;
            }
            set
            {
                this.OnIsDefaultChanging(value);
                this._IsDefault = value;
                this.OnIsDefaultChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Nullable<bool> _IsDefault;
        partial void OnIsDefaultChanging(global::System.Nullable<bool> value);
        partial void OnIsDefaultChanged();
        /// <summary>
        /// There are no comments for Property PagesUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("pagesUrl")]
        public string PagesUrl
        {
            get
            {
                return this._PagesUrl;
            }
            set
            {
                this.OnPagesUrlChanging(value);
                this._PagesUrl = value;
                this.OnPagesUrlChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _PagesUrl;
        partial void OnPagesUrlChanging(string value);
        partial void OnPagesUrlChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Self in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("self")]
        public string Self
        {
            get
            {
                return this._Self;
            }
            set
            {
                this.OnSelfChanging(value);
                this._Self = value;
                this.OnSelfChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Self;
        partial void OnSelfChanging(string value);
        partial void OnSelfChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("createdBy")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property LastModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("lastModifiedBy")]
        public string LastModifiedBy
        {
            get
            {
                return this._LastModifiedBy;
            }
            set
            {
                this.OnLastModifiedByChanging(value);
                this._LastModifiedBy = value;
                this.OnLastModifiedByChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _LastModifiedBy;
        partial void OnLastModifiedByChanging(string value);
        partial void OnLastModifiedByChanged();
        /// <summary>
        /// There are no comments for Property LastModifiedTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("lastModifiedTime")]
        public global::System.Nullable<global::System.DateTimeOffset> LastModifiedTime
        {
            get
            {
                return this._LastModifiedTime;
            }
            set
            {
                this.OnLastModifiedTimeChanging(value);
                this._LastModifiedTime = value;
                this.OnLastModifiedTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _LastModifiedTime;
        partial void OnLastModifiedTimeChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnLastModifiedTimeChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("id")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("createdTime")]
        public global::System.Nullable<global::System.DateTimeOffset> CreatedTime
        {
            get
            {
                return this._CreatedTime;
            }
            set
            {
                this.OnCreatedTimeChanging(value);
                this._CreatedTime = value;
                this.OnCreatedTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreatedTime;
        partial void OnCreatedTimeChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedTimeChanged();
        /// <summary>
        /// There are no comments for Property ParentNotebook in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("parentNotebook")]
        public global::Microsoft.OneNote.Api.Notebook ParentNotebook
        {
            get
            {
                return this._ParentNotebook;
            }
            set
            {
                this.OnParentNotebookChanging(value);
                this._ParentNotebook = value;
                this.OnParentNotebookChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OneNote.Api.Notebook _ParentNotebook;
        partial void OnParentNotebookChanging(global::Microsoft.OneNote.Api.Notebook value);
        partial void OnParentNotebookChanged();
        /// <summary>
        /// There are no comments for Property ParentSectionGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("parentSectionGroup")]
        public global::Microsoft.OneNote.Api.SectionGroup ParentSectionGroup
        {
            get
            {
                return this._ParentSectionGroup;
            }
            set
            {
                this.OnParentSectionGroupChanging(value);
                this._ParentSectionGroup = value;
                this.OnParentSectionGroupChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OneNote.Api.SectionGroup _ParentSectionGroup;
        partial void OnParentSectionGroupChanging(global::Microsoft.OneNote.Api.SectionGroup value);
        partial void OnParentSectionGroupChanged();
        /// <summary>
        /// There are no comments for Property Pages in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("pages")]
        public global::System.Collections.ObjectModel.Collection<global::Microsoft.OneNote.Api.Page> Pages
        {
            get
            {
                return this._Pages;
            }
            set
            {
                this.OnPagesChanging(value);
                this._Pages = value;
                this.OnPagesChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.OneNote.Api.Page> _Pages = new global::System.Collections.ObjectModel.Collection<global::Microsoft.OneNote.Api.Page>();
        partial void OnPagesChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.OneNote.Api.Page> value);
        partial void OnPagesChanged();
    }
    /// <summary>
    /// There are no comments for PageSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PageSingle")]
    public partial class PageSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Page>
    {
        /// <summary>
        /// Initialize a new PageSingle object.
        /// </summary>
        public PageSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PageSingle object.
        /// </summary>
        public PageSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
        /// <summary>
        /// There are no comments for ParentSection in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OneNote.Api.SectionSingle ParentSection
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ParentSection == null))
                {
                    this._ParentSection = new global::Microsoft.OneNote.Api.SectionSingle(this.Context, GetPath("parentSection"));
                }
                return this._ParentSection;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OneNote.Api.SectionSingle _ParentSection;
        /// <summary>
        /// There are no comments for ParentNotebook in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OneNote.Api.NotebookSingle ParentNotebook
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ParentNotebook == null))
                {
                    this._ParentNotebook = new global::Microsoft.OneNote.Api.NotebookSingle(this.Context, GetPath("parentNotebook"));
                }
                return this._ParentNotebook;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OneNote.Api.NotebookSingle _ParentNotebook;
    }
    /// <summary>
    /// There are no comments for Page in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Page")]
    public partial class Page
    {
        /// <summary>
        /// Create a new Page object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static Page CreatePage(string ID)
        {
            Page page = new Page();
            page.Id = ID;
            return page;
        }
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("title")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property CreatedByAppId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("createdByAppId")]
        public string CreatedByAppId
        {
            get
            {
                return this._CreatedByAppId;
            }
            set
            {
                this.OnCreatedByAppIdChanging(value);
                this._CreatedByAppId = value;
                this.OnCreatedByAppIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _CreatedByAppId;
        partial void OnCreatedByAppIdChanging(string value);
        partial void OnCreatedByAppIdChanged();
        /// <summary>
        /// There are no comments for Property Links in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("links")]
        public global::Microsoft.OneNote.Api.PageLinks Links
        {
            get
            {
                return this._Links;
            }
            set
            {
                this.OnLinksChanging(value);
                this._Links = value;
                this.OnLinksChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OneNote.Api.PageLinks _Links;
        partial void OnLinksChanging(global::Microsoft.OneNote.Api.PageLinks value);
        partial void OnLinksChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("id")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("createdTime")]
        public global::System.Nullable<global::System.DateTimeOffset> CreatedTime
        {
            get
            {
                return this._CreatedTime;
            }
            set
            {
                this.OnCreatedTimeChanging(value);
                this._CreatedTime = value;
                this.OnCreatedTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreatedTime;
        partial void OnCreatedTimeChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedTimeChanged();
        /// <summary>
        /// There are no comments for Property ParentSection in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("parentSection")]
        public global::Microsoft.OneNote.Api.Section ParentSection
        {
            get
            {
                return this._ParentSection;
            }
            set
            {
                this.OnParentSectionChanging(value);
                this._ParentSection = value;
                this.OnParentSectionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OneNote.Api.Section _ParentSection;
        partial void OnParentSectionChanging(global::Microsoft.OneNote.Api.Section value);
        partial void OnParentSectionChanged();
        /// <summary>
        /// There are no comments for Property ParentNotebook in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("parentNotebook")]
        public global::Microsoft.OneNote.Api.Notebook ParentNotebook
        {
            get
            {
                return this._ParentNotebook;
            }
            set
            {
                this.OnParentNotebookChanging(value);
                this._ParentNotebook = value;
                this.OnParentNotebookChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OneNote.Api.Notebook _ParentNotebook;
        partial void OnParentNotebookChanging(global::Microsoft.OneNote.Api.Notebook value);
        partial void OnParentNotebookChanged();
    }
    /// <summary>
    /// There are no comments for NotebookLinks in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("NotebookLinks")]
    public partial class NotebookLinks
    {
        /// <summary>
        /// There are no comments for Property OneNoteClientUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("oneNoteClientUrl")]
        public global::Microsoft.OneNote.Api.ExternalLink OneNoteClientUrl
        {
            get
            {
                return this._OneNoteClientUrl;
            }
            set
            {
                this.OnOneNoteClientUrlChanging(value);
                this._OneNoteClientUrl = value;
                this.OnOneNoteClientUrlChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OneNote.Api.ExternalLink _OneNoteClientUrl;
        partial void OnOneNoteClientUrlChanging(global::Microsoft.OneNote.Api.ExternalLink value);
        partial void OnOneNoteClientUrlChanged();
        /// <summary>
        /// There are no comments for Property OneNoteWebUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("oneNoteWebUrl")]
        public global::Microsoft.OneNote.Api.ExternalLink OneNoteWebUrl
        {
            get
            {
                return this._OneNoteWebUrl;
            }
            set
            {
                this.OnOneNoteWebUrlChanging(value);
                this._OneNoteWebUrl = value;
                this.OnOneNoteWebUrlChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OneNote.Api.ExternalLink _OneNoteWebUrl;
        partial void OnOneNoteWebUrlChanging(global::Microsoft.OneNote.Api.ExternalLink value);
        partial void OnOneNoteWebUrlChanged();
    }
    /// <summary>
    /// There are no comments for PageLinks in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PageLinks")]
    public partial class PageLinks
    {
        /// <summary>
        /// There are no comments for Property OneNoteClientUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("oneNoteClientUrl")]
        public global::Microsoft.OneNote.Api.ExternalLink OneNoteClientUrl
        {
            get
            {
                return this._OneNoteClientUrl;
            }
            set
            {
                this.OnOneNoteClientUrlChanging(value);
                this._OneNoteClientUrl = value;
                this.OnOneNoteClientUrlChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OneNote.Api.ExternalLink _OneNoteClientUrl;
        partial void OnOneNoteClientUrlChanging(global::Microsoft.OneNote.Api.ExternalLink value);
        partial void OnOneNoteClientUrlChanged();
        /// <summary>
        /// There are no comments for Property OneNoteWebUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("oneNoteWebUrl")]
        public global::Microsoft.OneNote.Api.ExternalLink OneNoteWebUrl
        {
            get
            {
                return this._OneNoteWebUrl;
            }
            set
            {
                this.OnOneNoteWebUrlChanging(value);
                this._OneNoteWebUrl = value;
                this.OnOneNoteWebUrlChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OneNote.Api.ExternalLink _OneNoteWebUrl;
        partial void OnOneNoteWebUrlChanging(global::Microsoft.OneNote.Api.ExternalLink value);
        partial void OnOneNoteWebUrlChanged();
    }
    /// <summary>
    /// There are no comments for ExternalLink in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ExternalLink")]
    public partial class ExternalLink
    {
        /// <summary>
        /// There are no comments for Property Href in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("href")]
        public string Href
        {
            get
            {
                return this._Href;
            }
            set
            {
                this.OnHrefChanging(value);
                this._Href = value;
                this.OnHrefChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Href;
        partial void OnHrefChanging(string value);
        partial void OnHrefChanged();
    }
    /// <summary>
    /// There are no comments for Diagnostic in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Diagnostic")]
    public partial class Diagnostic
    {
        /// <summary>
        /// There are no comments for Property Message in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("message")]
        public string Message
        {
            get
            {
                return this._Message;
            }
            set
            {
                this.OnMessageChanging(value);
                this._Message = value;
                this.OnMessageChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Message;
        partial void OnMessageChanging(string value);
        partial void OnMessageChanged();
        /// <summary>
        /// There are no comments for Property Url in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("url")]
        public string Url
        {
            get
            {
                return this._Url;
            }
            set
            {
                this.OnUrlChanging(value);
                this._Url = value;
                this.OnUrlChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Url;
        partial void OnUrlChanging(string value);
        partial void OnUrlChanged();
    }
    /// <summary>
    /// There are no comments for UserRole in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("UserRole")]
    public enum UserRole
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Owner")]
        Owner = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Contributor")]
        Contributor = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Reader")]
        Reader = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("None")]
        None = -1
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Microsoft.OneNote.Api.Notebook as global::Microsoft.OneNote.Api.NotebookSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.OneNote.Api.NotebookSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OneNote.Api.Notebook> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Microsoft.OneNote.Api.NotebookSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OneNote.Api.SectionGroup as global::Microsoft.OneNote.Api.SectionGroupSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.OneNote.Api.SectionGroupSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OneNote.Api.SectionGroup> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Microsoft.OneNote.Api.SectionGroupSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OneNote.Api.Section as global::Microsoft.OneNote.Api.SectionSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.OneNote.Api.SectionSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OneNote.Api.Section> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Microsoft.OneNote.Api.SectionSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OneNote.Api.Page as global::Microsoft.OneNote.Api.PageSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.OneNote.Api.PageSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OneNote.Api.Page> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Microsoft.OneNote.Api.PageSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
